package com.mall03.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.mall03.model.general.Shops;
import com.mall03.model.general.Users;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("users", "users_id", Users.class);
		arp.addMapping("shops", "shops_id", Shops.class);
	}
}

